server:
  port: 9000

spring:
  application:
    name: project-gateway
  profiles:
    active: cloud
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:}
        group: DEFAULT_GROUP
      config:
        server-addr: ${NACOS_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:}
        group: DEFAULT_GROUP
        file-extension: yml
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: project-system
          uri: lb://project-system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
        - id: project-auth
          uri: lb://project-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: project-admin
          uri: lb://project-admin
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
